# Site settings
title: Slides: Advanced Web Design
email: adam.scott@uconn.edu
description: "Slides for the advanced web design course at UConn Stamford"
baseurl: "/slides"
url: "http://advanced-web-design.github.io/slides"
twitter_username: adamdscott
github_username:  ascott1

# Build settings
markdown: kramdown
permalink: pretty
